name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # New dependencies for the implemented features
  share_plus: ^7.2.1
  timezone: ^0.9.1

  # Aula 03 - Novas dependências
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  sensors_plus: ^4.0.2
  vibration: ^2.0.0
  geolocator: ^11.0.1  # Versão mais recente
  geocoding: ^2.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true