# docker-compose.localstack.yml
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=rabbitmq
      - RABBITMQ_BIND_PORT=5672
      - RABBITMQ_MANAGEMENT_PORT=15672
      - DEBUG=1
    ports:
      - "4566:4566"  # LocalStack Edge Port
      - "5672:5672"  # RabbitMQ
      - "15672:15672" # RabbitMQ Management
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"